version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - checkout
      - run:
          name: dir structure info
          command: pwd && ls -al
  deploy-development:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: wirestock-api-dev
  deploy-staging:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: wirestock-api-stg
  deploy-production:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: wirestock-api-prod
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-development:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - hold_to_staging:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - deploy-development
      - deploy-staging:
          filters:
            branches:
              only: master
          requires:
            - hold_to_staging
      - hold_to_production:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - deploy-staging
      - deploy-production:
          filters:
            branches:
              only: master
          requires:
            - hold_to_production