version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - checkout
      - run:
          name: dir structure info
          command: pwd && ls -al
      - run:
          name: composer install
          command: composer install
  deploy-development:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: wirestock-api-dev
          command: ssh -vv -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_DEV_HOST} "cd /var/www/wirestock && git checkout master && git pull && sudo chmod a+x provision.sh && ./provision.sh"
  deploy-staging:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: wirestock-api-stg
          command: ssh -vv -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_STAGING_HOST} "cd /var/www/wirestock && git checkout master && git pull && sudo chmod a+x provision.sh && ./provision.sh"
  deploy-production:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: wirestock-api-prod
          command: ssh -vv -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_PRODUCTION_HOST} "cd /var/www/wirestock && git checkout master && git pull && sudo chmod a+x provision.sh && ./provision.sh"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-development:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - hold_to_staging:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - deploy-development
      - deploy-staging:
          filters:
            branches:
              only: master
          requires:
            - hold_to_staging
      - hold_to_production:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - deploy-staging
      - deploy-production:
          filters:
            branches:
              only: master
          requires:
            - hold_to_production